version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: src/OpenFTTH.GDBIntegrator
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: src/OpenFTTH.GDBIntegrator
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Test
          command: dotnet test
          working_directory: test/OpenFTTH.GDBIntegrator.Tests
