version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Apt update
          command: apt-get update;
      - run:
          name: Install make
          command: apt-get install make
      - run:
          name: Restore
          command: make restore
      - run:
          name: Build
          command: make build-release
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Apt update
          command: apt-get update;
      - run:
          name: Install make
          command: apt-get install make
      - run:
          name: Test
          command: make test

orbs:
  docker: circleci/docker@1.0.1

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: $GDB_INTEGRATOR_DOCKER_ORGANISATION/$GDB_INTEGRATOR_DOCKER_REPONAME
          docker-username: GDB_INTEGRATOR_DOCKER_LOGIN
          docker-password: GDB_INTEGRATOR_DOCKER_PASSWORD
          requires:
            - build_and_test
