version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Apt update
          command: apt-get update;
      - run:
          name: Install make
          command: apt-get install make
      - run:
          name: Restore
          command: make restore
      - run:
          name: Build
          command: make build-release
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Apt update
          command: apt-get update;
      - run:
          name: Install make
          command: apt-get install make
      - run:
          name: Test
          command: make test
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
