namespace OpenFTTH.GDBIntegrator.Config;

public static class ErrorCode
{
    public const string LINE_STRING_IS_INVALID = "LINE_STRING_IS_INVALID";
    public const string LINE_STRING_IS_NOT_SIMPLE = "LINE_STRING_IS_NOT_SIMPLE";
    public const string LINE_STRING_IS_CLOSED = "LINE_STRING_IS_CLOSED";
    public const string LINE_STRING_ENDS_CLOSER_TO_EACH_OTHER_THAN_TOLERANCE = "LINE_STRING_ENDS_CLOSER_TO_EACH_OTHER_THAN_TOLERANCE";
    public const string LINE_STRING_ENDS_CLOSER_TO_THE_EDGE_THAN_TOLERANCE = "LINE_STRING_ENDS_CLOSER_TO_THE_EDGE_THAN_TOLERANCE";
    public const string ROUTE_SEGMENT_INTERSECTS_WITH_MULTIPLE_START_OR_END_ROUTE_NODES = "ROUTE_SEGMENT_INTERSECTS_WITH_MULTIPLE_START_OR_END_ROUTE_NODES";
    public const string RECEIVED_INVALID_MESSAGE = "RECEIVED_INVALID_MESSAGE";
    public const string UNKNOWN_ERROR = "UNKNOWN_ERROR";
    public const string ROUTE_NODE_INTERSECTS_WITH_ANOTHER_ROUTE_NODE = "ROUTE_NODE_INTERSECTS_WITH_ANOTHER_ROUTE_NODE";
}
