namespace OpenFTTH.GDBIntegrator.Config;

public static class ErrorCode
{
    public const string LINE_STRING_IS_INVALID = "LINE_STRING_IS_INVALID";
    public const string LINE_STRING_IS_NOT_SIMPLE = "LINE_STRING_IS_NOT_SIMPLE";
    public const string LINE_STRING_IS_CLOSED = "LINE_STRING_IS_CLOSED";
    public const string LINE_STRING_ENDS_CLOSER_TO_EACH_OTHER_THAN_TOLERANCE = "LINE_STRING_ENDS_CLOSER_TO_EACH_OTHER_THAN_TOLERANCE";
    public const string LINE_STRING_ENDS_CLOSER_TO_THE_EDGE_THAN_TOLERANCE = "LINE_STRING_ENDS_CLOSER_TO_THE_EDGE_THAN_TOLERANCE";
    public const string ROUTE_SEGMENT_INTERSECTS_WITH_MULTIPLE_START_OR_END_ROUTE_NODES = "ROUTE_SEGMENT_INTERSECTS_WITH_MULTIPLE_START_OR_END_ROUTE_NODES";
    public const string RECEIVED_INVALID_MESSAGE = "RECEIVED_INVALID_MESSAGE";
    public const string UNKNOWN_ERROR = "UNKNOWN_ERROR";
    public const string ROUTE_NODE_INTERSECTS_WITH_ANOTHER_ROUTE_NODE = "ROUTE_NODE_INTERSECTS_WITH_ANOTHER_ROUTE_NODE";
    public const string ROUTE_NODE_CANNOT_MODIFY_GEOMETRY_AND_MARK_FOR_DELETION_IN_THE_SAME_OPERATION = "ROUTE_NODE_CANNOT_MODIFY_GEOMETRY_AND_MARK_FOR_DELETION_IN_THE_SAME_OPERATION";
    public const string USER_HAS_NOT_SELECTED_A_WORK_TASK = "USER_HAS_NOT_SELECTED_A_WORK_TASK";
    public const string MESSAGE_IS_MISSING_USERNAME = "MESSAGE_IS_MISSING_USERNAME";
    public const string ROUTE_NODE_GEOMETRY_UPDATE_NOT_ALLOWED_TO_INTERSECT_WITH_ROUTE_SEGMENT = "ROUTE_NODE_GEOMETRY_UPDATE_NOT_ALLOWED_TO_INTERSECT_WITH_ROUTE_SEGMENT";
    public const string ROUTE_NODE_INTERSECT_WITH_ROUTE_SEGMENT_CANNOT_BE_DELETED =  "ROUTE_NODE_INTERSECT_WITH_ROUTE_SEGMENT_CANNOT_BE_DELETED";
    public const string CANNOT_DELETE_ROUTE_NODE_WITH_RELATED_EQUIPMENT = "CANNOT_DELETE_ROUTE_NODE_WITH_RELATED_EQUIPMENT";
    public const string CANNOT_DELETE_ROUTE_SEGMENT_WITH_RELATED_EQUIPMENT = "CANNOT_DELETE_ROUTE_SEGMENT_WITH_RELATED_EQUIPMENT";
    public const string ROUTE_NODE_MODIFIED_LESS_THAN_TOLERANCE = "ROUTE_NODE_MODIFIED_LESS_THAN_TOLERANCE";
    public const string CANNOT_CHANGE_CONNECTIVITY_ROUTE_SEGMENT_WITH_RELATED_EQUIPMENT = "CANNOT_CHANGE_CONNECTIVITY_ROUTE_SEGMENT_WITH_RELATED_EQUIPMENT";
}
